/**
 * Copyright 2006-2008 by Amplafi. All rights reserved.
 * Confidential.
 */
package org.amplafi.flow;

/**
 * Used to provide a smarter way generating a FlowProperty value than just deserializing.
 * This will be used to avoid having to override getProperty()/setProperty().
 *
 * TODO hook this in some how with the FlowPropertyBinding use of @Parameter(defaultValue="")
 * @author patmoore
 * @param <FA> extends {@link FlowActivity}.
 *
 */
public interface FlowPropertyValueProvider<FA extends FlowActivity> {
    /**
     *
     * @param <T> type of object returned
     * @param flowActivity current FlowActivity -- be careful will not always be the FlowActivity that created this FlowPropertyValueProvider
     * @param flowPropertyDefinition
     * @return object generated by this provider
     */
    public <T> T get(FA flowActivity, FlowPropertyDefinition flowPropertyDefinition);
}
