/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
 * OR CONDITIONS OF ANY KIND, either express or implied. See the License for
 * the specific language governing permissions and limitations under the
 * License.
 */

package org.amplafi.flow;

/**
 * Used to provide a smarter way generating a FlowProperty value than just deserializing.
 * This will be used to avoid having to override {@link FlowActivity#getProperty(String)}/ {@link FlowActivity#setProperty(String, Object)}.
 *
 * TODO: enable FlowPropertyValueProvider to be registered so they can be singletons with needed services injected vis the DI framework.
 * TODO: enable the FPVP to provide a template {@link FlowPropertyDefinition} that can be then customized with a given flow's specific
 * PropertyRequired values.
 *
 * TODO hook this in some how with the FlowPropertyBinding use of @Parameter(defaultValue="")
 * @author patmoore
 * @param <FA> extends {@link FlowActivity}.
 *
 */
public interface FlowPropertyValueProvider<FA extends FlowActivity> {
    /**
     *
     * @param <T> type of object returned
     * @param flowActivity current FlowActivity -- be careful will not always be the FlowActivity that created this FlowPropertyValueProvider
     * @param flowPropertyDefinition
     * @return object generated by this provider
     */
    <T> T get(FA flowActivity, FlowPropertyDefinition flowPropertyDefinition);
}
